apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster/infrastructure-metallb.yaml
  - cluster/infrastructure-seaweedfs-csi-driver-kustomization.yaml
  - cluster/infrastructure-seaweedfs-kustomization.yaml
  - cluster/infrastructure-traefik.yaml
  - cluster/infrastructure-gpu-device-plugin-kustomization.yaml
  - cluster/infrastructure-descheduler-kustomization.yaml
  - cluster/apps-kustomization.yaml
