apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster/infrastructure-metallb.yaml
  - cluster/infrastructure-storage.yaml
  - cluster/infrastructure-seaweedfs-helmrepository.yaml
  - cluster/infrastructure-seaweedfs-helmrelease.yaml
  - cluster/infrastructure-seaweedfs-values-configmap.yaml
  - cluster/infrastructure-seaweedfs-kustomization.yaml
  - cluster/infrastructure-seaweedfs-csi-kustomization.yaml
  - cluster/infrastructure-traefik.yaml
  - cluster/apps-kustomization.yaml
