apiVersion: v1
kind: Service
metadata:
  name: pluto-for-channels
  namespace: live
  labels:
    app: pluto-for-channels
spec:
  type: ClusterIP
  selector:
    app: pluto-for-channels
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
