apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatcharr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dispatcharr.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dispatcharr
                port:
                  number: 9191
