apiVersion: v1
kind: Service
metadata:
  name: dispatcharr
  namespace: media
  labels:
    app: dispatcharr
spec:
  type: ClusterIP
  selector:
    app: dispatcharr
  ports:
    - port: 9191
      targetPort: 9191
      protocol: TCP
      name: http
