apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./metallb
  - ./traefik
  - ./storage
  - ./fencing
  # seaweedfs removed - migrating to Longhorn
  # seaweedfs-operator removed - migrated to direct Helm chart in ./seaweedfs
