apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eplustv
  namespace: live
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: http
spec:
  ingressClassName: traefik
  rules:
    - host: eplustv.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eplustv
                port:
                  number: 8000
