apiVersion: v1
kind: Service
metadata:
  name: eplustv
  namespace: live
  labels:
    app: eplustv
spec:
  type: ClusterIP
  selector:
    app: eplustv
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
