apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-channels-dvr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-simple
  resources:
    requests:
      storage: 20Gi
