apiVersion: v1
kind: Service
metadata:
  name: channels-dvr
  namespace: media
  labels:
    app: channels-dvr
spec:
  type: ClusterIP
  selector:
    app: channels-dvr
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
