apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamarr
  namespace: live
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: teamarr.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teamarr
                port:
                  number: 9195
