apiVersion: v1
kind: Service
metadata:
  name: teamarr
  namespace: live
  labels:
    app: teamarr
spec:
  type: ClusterIP
  selector:
    app: teamarr
  ports:
    - port: 9195
      targetPort: 9195
      protocol: TCP
      name: http
