apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterplex-orchestrator-config
  namespace: media
  labels:
    app.kubernetes.io/name: clusterplex-orchestrator-config
    app.kubernetes.io/part-of: clusterplex
data:
  TZ: America/Chicago
  LISTENING_PORT: "3500"
  WORKER_SELECTION_STRATEGY: LOAD_TASKS
