apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/homelab/apps
  prune: true
  wait: true
  timeout: 3m
  dependsOn:
    - name: infrastructure-storage
    - name: operations
  sourceRef:
    kind: GitRepository
    name: flux-system
  
