apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/homelab/infrastructure/traefik
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
