apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-descheduler
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/homelab/infrastructure/descheduler
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
