apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-seaweedfs
  namespace: flux-system
spec:
  # Depends on metallb and traefik being ready
  dependsOn:
    - name: infrastructure-metallb
    - name: infrastructure-traefik
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/homelab/infrastructure/seaweedfs
