apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-seaweedfs-csi
  namespace: flux-system
spec:
  # Deploy CSI after the seaweedfs backend is ready
  dependsOn:
    - name: infrastructure-seaweedfs
  interval: 1m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/homelab/infrastructure/seaweedfs-csi
