apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operations
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/homelab/operations
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: infrastructure-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
