apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.50-192.168.1.98
---
apiVersion: metallb.io/v1beta1
kind: BGPPeer
metadata:
  name: udm
  namespace: metallb-system
spec:
  peerAddress: 192.168.1.1
  peerASN: 65000
  myASN: 65001
  holdTime: 180s
  keepaliveTime: 60s
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
  peers:
  - udm
