apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds-and-ns.yaml
  - rbac.yaml
  - webhook-secret.yaml
  - deployments.yaml
  - config.yaml

commonLabels:
  app: metallb

