apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: seaweedfs-csi
  namespace: seaweedfs
namespace: seaweedfs
resources:
  - serviceaccounts-and-rbac.yaml
  - csidriver.yaml
  - controller.yaml
  - node-and-mount.yaml
commonLabels:
  app.kubernetes.io/name: seaweedfs-csi-driver
  app.kubernetes.io/part-of: seaweedfs
