apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  path: ../../apps
  prune: true
  wait: true
  timeout: 3m
  dependsOn:
    - name: cluster-addons-controllers
    - name: operations
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
