apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-addons-controllers
  namespace: flux-system
spec:
  interval: 1m
  path: ../../cluster-addons/controllers
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: cluster-addons-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
