apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-addons-crds
  namespace: flux-system
spec:
  interval: 1m
  path: ../../cluster-addons/crds
  prune: true
  wait: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
