apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operations
  namespace: flux-system
spec:
  interval: 1m
  path: ../../operations
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
