---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: seaweedfs-csi-driver
  namespace: seaweedfs-csi-driver
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - storageclass.yaml
  - storageclass-single.yaml
  - storageclass-rwx.yaml
