apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-sonarr-primary.yaml
  - pv-sonarr-backup.yaml
  - pv-volsync-sonarr-config.yaml
  - pv-prowlarr-primary.yaml
  - pv-prowlarr-backup.yaml
  - pv-volsync-prowlarr-config.yaml
