apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volsync-prowlarr-primary-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/volsync/prowlarr-primary-config
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - primary
  claimRef:
    namespace: media
    name: volsync-prowlarr-primary-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volsync-prowlarr-backup-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/volsync/prowlarr-backup-config
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - backup
  claimRef:
    namespace: media
    name: volsync-prowlarr-backup-config
