---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs-operator
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - ../seaweedfs/namespace.yaml  # Reuse existing seaweedfs namespace
  - seaweed.yaml
