apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pluto-for-channels
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: pluto.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pluto-for-channels
                port:
                  number: 8080
