apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-config-w3
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-plex-config-w3
  resources:
    requests:
      storage: 10Gi
