apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-plex-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-nfs-plex-config
  resources:
    requests:
      storage: 10Gi
