apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/part-of: plex
spec:
  type: ClusterIP
  ports:
    - name: pms
      port: 32400
      targetPort: pms
      protocol: TCP
  selector:
    app.kubernetes.io/name: plex
