---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fuse-test

commonLabels:
  testing: "true"
  component: fuse-propagation-test

commonAnnotations:
  description: "FUSE propagation test - experimental, non-production"
  test-date: "2026-02-28"

resources:
  - namespace.yaml
  - producer.yaml
  - consumer.yaml

# Note: This test is managed by Flux when enabled in the parent testing/kustomization.yaml
