apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ./channels-dvr
  - ./pluto-for-channels
  - ./eplustv
  - ./dispatcharr
  - ./teamarr

patches:
  - path: ../patches/ha-affinity.yaml
    target:
      kind: StatefulSet
  - path: ../patches/statefulset-strategy.yaml
    target:
      kind: StatefulSet
  - path: ../patches/disable-service-links.yaml
    target:
      kind: StatefulSet
