apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operations

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - rbac.yaml
  - pdb.yaml

commonLabels:
  app: failover-api
  component: operations
