apiVersion: v1
kind: Service
metadata:
  name: failover-api
  namespace: operations
  labels:
    app: failover-api
spec:
  type: ClusterIP
  selector:
    app: failover-api
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None
