apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: victoria-logs-victoria-logs-single-server
      namespace: victoria-logs
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.longhorn.io/create-default-disk: "true"
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node.longhorn.io/storage
            operator: Equal
            value: enabled
            effect: NoSchedule
