apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: channels-dvr
  namespace: live
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: http
spec:
  ingressClassName: traefik
  rules:
    - host: channels.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: channels-dvr
                port:
                  number: 8089
