apiVersion: v1
kind: Service
metadata:
  name: channels-dvr
  namespace: live
  labels:
    app: channels-dvr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.110
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: channels-dvr
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
