apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - seaweed.yaml
  - ../storage/nfs/pv-nfs-media.yaml
  - ../storage/nfs/pv-nfs-transcode.yaml

commonLabels:
  app: seaweedfs
